language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

jobs:
  include:
    - stage: Compile
      script:
        - autoreconf -iv
        - ./configure --enable-Werror --enable-code-coverage
        - make -j8
    - stage: Test
      script:
        - make check 2>&1 | tail -10000
    - stage: Dist Check
      script:
        - make distcheck

after_success:
  - test "x$CC" = "xgcc" -o "x$CC" = "xclang" && make code-coverage-capture && coveralls-lcov asn1c-*-coverage.info
